### ISSUE TITLE
Tide wont work on 64-bit systems

### ISSUE THREAD

**Issue by soumith** [bitRadio/Tide#2]
The main issue is the code here:

https://github.com/andresy/luajit/blob/master/src/lib_aux.c#L346

which is used by tide here:

https://github.com/bitRadio/tide/blob/master/src/mod_lua.inl#L1284
https://github.com/bitRadio/tide/blob/master/src/mod_lua.inl#L1179
https://github.com/bitRadio/tide/blob/master/src/mod_lua.inl#L1231

Using a custom allocator mg_alloc/mg_free is not allowed by luajit in 64-bit mode looks like it.

**Comment by soumith** [comment]
I suppose this is on OSX.

More reading here:
https://gist.github.com/nddrylliog/8722197

**Comment by soumith** [comment]
Nope, cross-checked with Linux, same issue.

**Comment by alisabri** [comment]
Hi,
I updated code for 64bit and osx, tested on ubuntu 14.04 and OS X Yosemite Version 10.10.4 (MacBook Pro 2.4GHz Intel Core i5) with chrome and firefox (safari fails)

**Comment by soumith** [comment]
this is great. finally got it working. A minor issue, you seem to link against luajit-5.1 whereas the stuff we ship has the library libluajit, not libluajit-5.1

Also, your instructions seem to use a global install of torch (sudo luarocks install xxx), whereas the default torch install is local, so no sudo necessary.
